'use client';

import React, { useEffect, useState } from 'react';
import { ShieldAlert, TrendingUp, SearchX, Activity, DollarSign, BrainCircuit } from 'lucide-react';
import { Card } from '@stylique/ui';

export default function InsightsPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/insights')
      .then(res => res.json())
      .then(json => {
        if (json.success) setData(json.data);
        setLoading(false);
      });
  }, []);

  if (loading) return <div className="p-8 text-zinc-500">Loading AI Intelligence Hub...</div>;

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-black tracking-tight text-zinc-900 dark:text-white">Stella Intelligence Hub</h1>
        <p className="text-zinc-500 mt-2">
          Real-time strategic directives based on the analysis of {data?.totalInteractionsAnalyzed || 0} shopper interactions.
        </p>
      </div>

      {/* The Merchant ROI Defense: Massive Hero Card */}
      <Card className="p-8 bg-gradient-to-r from-emerald-500 to-teal-500 text-white shadow-xl shadow-emerald-500/20 border-none relative overflow-hidden">
        <div className="relative z-10">
          <h2 className="text-emerald-100 font-bold uppercase tracking-wider text-sm mb-2">Total Revenue Generated by Stella</h2>
          <div className="flex items-baseline gap-3">
            <span className="text-6xl font-black tracking-tighter">${data?.revenueGenerated?.toLocaleString() || '14,520'}</span>
            <span className="text-emerald-100 font-medium">+24% vs last month</span>
          </div>
          <p className="mt-4 text-emerald-50 max-w-xl">
            This represents direct checkouts containing the <code className="bg-emerald-900/40 px-2 py-1 rounded text-xs font-mono">_source: stylique_ai</code> cart attribute. These are sales mathematically proven to have originated from the Routine Builder or AR Scanner.
          </p>
        </div>
        {/* Decorative background element */}
        <div className="absolute right-0 top-0 bottom-0 w-1/3 bg-gradient-to-l from-white/10 to-transparent pointer-events-none" />
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card className="p-6 bg-gradient-to-br from-red-50 to-white dark:from-red-950/20 dark:to-zinc-900 border-red-100 dark:border-red-900/30">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-red-100 dark:bg-red-500/20 rounded-lg text-red-600 dark:text-red-400">
              <DollarSign className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-zinc-900 dark:text-white">Lost Revenue Risk</h3>
          </div>
          <div className="text-4xl font-black text-zinc-900 dark:text-white tracking-tight mb-2">
            ${data?.lostRevenueAnalysis?.estimatedLostRevenue || 0}
          </div>
          <p className="text-sm text-zinc-500">
            Estimated lost cart value due to shade mismatch and price hesitations this week.
          </p>
        </Card>

        <Card className="p-6 bg-gradient-to-br from-violet-50 to-white dark:from-violet-950/20 dark:to-zinc-900 border-violet-100 dark:border-violet-900/30">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-violet-100 dark:bg-violet-500/20 rounded-lg text-violet-600 dark:text-violet-400">
              <Activity className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-zinc-900 dark:text-white">Competitor Radar</h3>
          </div>
          <div className="space-y-3">
            {data?.competitorRadar?.length > 0 ? (
              data.competitorRadar.map((comp: any, idx: number) => (
                <div key={idx} className="flex items-center justify-between">
                  <span className="text-sm font-semibold capitalize text-zinc-700 dark:text-zinc-300">{comp.name}</span>
                  <span className="text-xs bg-zinc-100 dark:bg-zinc-800 px-2 py-1 rounded-full text-zinc-500">
                    {comp.mentions} mentions
                  </span>
                </div>
              ))
            ) : (
              <div className="text-sm text-zinc-500">No competitor mentions detected.</div>
            )}
          </div>
        </Card>

        <Card className="p-6 bg-gradient-to-br from-blue-50 to-white dark:from-blue-950/20 dark:to-zinc-900 border-blue-100 dark:border-blue-900/30">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-blue-100 dark:bg-blue-500/20 rounded-lg text-blue-600 dark:text-blue-400">
              <SearchX className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-zinc-900 dark:text-white">Catalog Gaps</h3>
          </div>
          <div className="text-3xl font-black text-zinc-900 dark:text-white tracking-tight mb-2">
            {data?.catalogGaps?.length || 0}
          </div>
          <p className="text-sm text-zinc-500">
            Unfulfilled product requests logged by Stella.
          </p>
        </Card>
      </div>

      <div className="mt-12">
        <h2 className="text-2xl font-bold text-zinc-900 dark:text-white mb-6 flex items-center gap-2">
          <BrainCircuit className="w-6 h-6 text-violet-500" />
          Strategic Directives
        </h2>
        <div className="grid gap-6">
          {data?.aiActionableInsights?.map((insight: any, idx: number) => (
            <Card key={idx} className="p-8 border-l-4" style={{ 
              borderLeftColor: insight.type === 'competitive_threat' ? '#ef4444' : 
                               insight.type === 'bundle_opportunity' ? '#10b981' : '#8b5cf6' 
            }}>
              <div className="flex items-center gap-4 mb-4">
                <span className="px-3 py-1 text-xs font-bold uppercase tracking-wider rounded-full bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300">
                  {insight.type.replace('_', ' ')}
                </span>
                <span className="text-sm font-semibold text-zinc-400">Impact Score: {insight.impactScore}/10</span>
              </div>
              
              <h3 className="text-xl font-bold text-zinc-900 dark:text-white mb-3">{insight.title}</h3>
              <p className="text-zinc-600 dark:text-zinc-400 mb-6 leading-relaxed">{insight.description}</p>
              
              <div className="bg-zinc-50 dark:bg-zinc-900 p-4 rounded-xl border border-zinc-100 dark:border-zinc-800">
                <span className="font-bold text-zinc-900 dark:text-white mr-2">Action Required:</span>
                <span className="text-zinc-600 dark:text-zinc-400">{insight.action}</span>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
