import type { Product } from '@stylique/types';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Velvet Veil Foundation',
    description: 'A lightweight, buildable foundation that blurs imperfections and lasts 24 hours. Infused with hyaluronic acid for all-day hydration.',
    category: 'foundation',
    brand: 'Stylique',
    price: 42.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['buildable', 'long-wear', 'hydrating', 'all-skin-types'],
    shades: [
      { id: 'sh-001', productId: 'prod-001', name: 'Porcelain', hexColor: '#FDECD3', undertone: 'neutral', skinToneDepth: ['fair'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-002', productId: 'prod-001', name: 'Ivory', hexColor: '#F5D5A8', undertone: 'warm', skinToneDepth: ['fair', 'light'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-003', productId: 'prod-001', name: 'Sand', hexColor: '#EAC99A', undertone: 'neutral', skinToneDepth: ['light'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-004', productId: 'prod-001', name: 'Warm Beige', hexColor: '#D4956A', undertone: 'warm', skinToneDepth: ['medium'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-005', productId: 'prod-001', name: 'Golden Tan', hexColor: '#C0784A', undertone: 'warm', skinToneDepth: ['medium', 'tan'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-006', productId: 'prod-001', name: 'Espresso', hexColor: '#6B3A18', undertone: 'warm', skinToneDepth: ['deep', 'rich'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-007', productId: 'prod-001', name: 'Ebony', hexColor: '#3C1E0A', undertone: 'neutral', skinToneDepth: ['rich'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-008', productId: 'prod-001', name: 'Rose Beige', hexColor: '#E8C0A8', undertone: 'cool', skinToneDepth: ['light', 'medium'], imageUrl: null, inStock: true, price: null },
    ],
    inStock: true,
    url: null,
    ingredients: 'Aqua, Dimethicone, Hyaluronic Acid, Niacinamide, SPF 15',
    spf: 15,
    isVegan: true,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-002',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Petal Perfection Blush',
    description: 'A silky powder blush that delivers a natural flush of colour. Buildable from sheer to vivid intensity.',
    category: 'blush',
    brand: 'Stylique',
    price: 28.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['powder', 'buildable', 'natural-finish'],
    shades: [
      { id: 'sh-009', productId: 'prod-002', name: 'Rose Quartz', hexColor: '#F0B5BE', undertone: 'cool', skinToneDepth: ['fair', 'light'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-010', productId: 'prod-002', name: 'Peach Bloom', hexColor: '#F5A880', undertone: 'warm', skinToneDepth: ['light', 'medium'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-011', productId: 'prod-002', name: 'Berry Bliss', hexColor: '#C4608A', undertone: 'cool', skinToneDepth: ['medium', 'tan', 'deep'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-012', productId: 'prod-002', name: 'Terracotta', hexColor: '#C87860', undertone: 'warm', skinToneDepth: ['tan', 'deep', 'rich'], imageUrl: null, inStock: true, price: null },
    ],
    inStock: true,
    url: null,
    ingredients: null,
    spf: null,
    isVegan: true,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-003',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Matte Luxe Lipstick',
    description: 'A rich, creamy lipstick with a velvety matte finish. Formulated with vitamin E for comfortable all-day wear.',
    category: 'lipstick',
    brand: 'Stylique',
    price: 24.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1586495204481-2292f3922c26?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['matte', 'long-wear', 'vitamin-e', 'comfortable'],
    shades: [
      { id: 'sh-013', productId: 'prod-003', name: 'Nude Satin', hexColor: '#C8906A', undertone: 'warm', skinToneDepth: ['fair', 'light', 'medium'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-014', productId: 'prod-003', name: 'Dusty Rose', hexColor: '#C08090', undertone: 'cool', skinToneDepth: ['light', 'medium'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-015', productId: 'prod-003', name: 'Berry Wine', hexColor: '#703050', undertone: 'cool', skinToneDepth: ['medium', 'tan', 'deep', 'rich'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-016', productId: 'prod-003', name: 'Coral Kiss', hexColor: '#E86050', undertone: 'warm', skinToneDepth: ['light', 'medium', 'tan'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-017', productId: 'prod-003', name: 'Ruby Red', hexColor: '#A01828', undertone: 'cool', skinToneDepth: ['fair', 'light', 'medium', 'tan', 'deep', 'rich'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-018', productId: 'prod-003', name: 'Mocha Dream', hexColor: '#80402A', undertone: 'warm', skinToneDepth: ['tan', 'deep', 'rich'], imageUrl: null, inStock: true, price: null },
    ],
    inStock: true,
    url: null,
    ingredients: null,
    spf: null,
    isVegan: true,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-004',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Luminous Glow Highlighter',
    description: 'A finely-milled powder highlighter that gives a blinding, glass-skin finish. Buildable intensity for every look.',
    category: 'highlighter',
    brand: 'Stylique',
    price: 32.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['glow', 'dewy', 'luminous', 'powder'],
    shades: [
      { id: 'sh-019', productId: 'prod-004', name: 'Champagne Toast', hexColor: '#F5D888', undertone: 'warm', skinToneDepth: ['fair', 'light'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-020', productId: 'prod-004', name: 'Rose Gold', hexColor: '#E8A080', undertone: 'warm', skinToneDepth: ['light', 'medium', 'tan'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-021', productId: 'prod-004', name: 'Bronze Goddess', hexColor: '#C07830', undertone: 'warm', skinToneDepth: ['tan', 'deep', 'rich'], imageUrl: null, inStock: true, price: null },
    ],
    inStock: true,
    url: null,
    ingredients: null,
    spf: null,
    isVegan: true,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-005',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Flawless Skin Concealer',
    description: 'A full-coverage concealer that covers dark circles, blemishes and imperfections. Infused with caffeine to de-puff.',
    category: 'concealer',
    brand: 'Stylique',
    price: 26.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['full-coverage', 'long-wear', 'caffeine', 'brightening'],
    shades: [
      { id: 'sh-022', productId: 'prod-005', name: 'Fair 1', hexColor: '#FDECD3', undertone: 'neutral', skinToneDepth: ['fair'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-023', productId: 'prod-005', name: 'Light 2W', hexColor: '#F5D5A8', undertone: 'warm', skinToneDepth: ['light'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-024', productId: 'prod-005', name: 'Medium 3N', hexColor: '#D4956A', undertone: 'neutral', skinToneDepth: ['medium'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-025', productId: 'prod-005', name: 'Tan 4W', hexColor: '#A0622A', undertone: 'warm', skinToneDepth: ['tan'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-026', productId: 'prod-005', name: 'Deep 5C', hexColor: '#6B3A18', undertone: 'cool', skinToneDepth: ['deep'], imageUrl: null, inStock: true, price: null },
    ],
    inStock: true,
    url: null,
    ingredients: null,
    spf: null,
    isVegan: true,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-006',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Silk Finish Primer',
    description: 'A weightless primer that minimises pores, blurs fine lines and extends makeup wear up to 12 hours.',
    category: 'primer',
    brand: 'Stylique',
    price: 36.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['pore-minimising', 'long-wear', 'lightweight'],
    shades: [],
    inStock: true,
    url: null,
    ingredients: null,
    spf: null,
    isVegan: true,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-007',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Sculpt & Define Bronzer',
    description: 'A sun-kissed bronzer for natural warmth and definition. Buildable for subtle glow or full contour.',
    category: 'bronzer',
    brand: 'Stylique',
    price: 30.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1590156546946-ce55a12a6a5d?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['bronzer', 'contour', 'warm', 'buildable'],
    shades: [
      { id: 'sh-027', productId: 'prod-007', name: 'Light Sunkiss', hexColor: '#E8B882', undertone: 'warm', skinToneDepth: ['fair', 'light'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-028', productId: 'prod-007', name: 'Medium Bronze', hexColor: '#C08040', undertone: 'warm', skinToneDepth: ['medium', 'tan'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-029', productId: 'prod-007', name: 'Deep Mahogany', hexColor: '#804020', undertone: 'warm', skinToneDepth: ['deep', 'rich'], imageUrl: null, inStock: true, price: null },
    ],
    inStock: true,
    url: null,
    ingredients: null,
    spf: null,
    isVegan: true,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-008',
    brandId: 'demo-brand',
    externalId: null,
    name: 'Smoke & Mirrors Eyeshadow Palette',
    description: '12 curated shades from matte neutrals to metallic statements. Intensely pigmented for all-day wear.',
    category: 'eyeshadow',
    brand: 'Stylique',
    price: 54.00,
    currency: 'GBP',
    imageUrl: 'https://images.unsplash.com/photo-1583241495940-2e45f9fb0933?q=80&w=800&auto=format&fit=crop',
    images: [],
    tags: ['palette', 'matte', 'metallic', 'pigmented', 'neutral'],
    shades: [
      { id: 'sh-030', productId: 'prod-008', name: 'Warm Neutrals', hexColor: '#C8906A', undertone: 'warm', skinToneDepth: ['fair', 'light', 'medium', 'tan', 'deep', 'rich'], imageUrl: null, inStock: true, price: null },
      { id: 'sh-031', productId: 'prod-008', name: 'Cool Smokes', hexColor: '#686878', undertone: 'cool', skinToneDepth: ['fair', 'light', 'medium', 'tan', 'deep', 'rich'], imageUrl: null, inStock: true, price: null },
    ],
    inStock: true,
    url: null,
    ingredients: null,
    spf: null,
    isVegan: false,
    isCrueltyFree: true,
    lifespanDays: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
